# Generated by Django 4.1 on 2023-03-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partygame", "0003_partygamepost_category2_partygamepost_category3_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="partygamepost",
            name="preparation",
            field=models.TextField(default=1, verbose_name="準備事項"),
            preserve_default=False,
        ),
    ]
